{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "##To do: \n",
    "# Send yourself an email with as much information as possible from the site, such as:\n",
    "# The title of the thing (the sale, the article, whatever)\n",
    "# A URL for it\n",
    "# Upvotes/thumbs ups/subreddits/prices/links to images/etc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'{\\n  \"message\": \"Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings.\"\\n}'"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response = requests.post(\n",
    "        \"https://api.mailgun.net/v3/sandbox5ec0ddffbdba4001b8214f98622fe1d0.mailgun.org/messages\",\n",
    "        auth=(\"api\", \"6fdb842f47e65d63dd61f10b38545e63-2b778fc3-8157d877\"),\n",
    "        data={\"from\": \"Excited User <mailgun@sandbox5ec0ddffbdba4001b8214f98622fe1d0.mailgun.org>\",\n",
    "              \"to\": [\"giovanacfleck@gmail.com\", \"YOU@sandbox5ec0ddffbdba4001b8214f98622fe1d0.mailgun.org\"],\n",
    "              \"subject\": \"Hello\",\n",
    "              \"text\": \"Testing some Mailgun awesomness!\"}) \n",
    "response.text\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "response = requests.get('https://slickdeals.net')\n",
    "doc = BeautifulSoup(response.text, 'html.parser')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "62"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "products = doc.find_all(class_='fpItem')\n",
    "len(products)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " \n",
      " \n",
      " \n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[{'title': '', 'store': '\\xa0'},\n",
       " {'title': 'The Children&aposs Place&colon Up to 80&percnt Off Kid&aposs Clothing&colon Boys&apos and Girls&apos Tees',\n",
       "  'store': \"The Children's Place\\xa0\",\n",
       "  'price': '\\n                                          from $2\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13171879-children-s-place-up-to-80-off-sale-boys-and-girls-tees-from-2-big-girls-graphic-flip-flops-from-1-50-more-free-shipping?src=frontpage'},\n",
       " {'title': '50-Ct Wilton 12\" Disposable Cake Decorating Pastry Bags',\n",
       "  'store': 'Walmart\\xa0',\n",
       "  'price': '\\n                                          $5.80\\n                                                                                  $14\\n',\n",
       "  'link': 'https://slickdeals.net/f/13142320-50-count-wilton-12-inch-disposable-cake-decorating-bags-5-81-free-store-pickup-at-walmart-fs-for-prime?src=frontpage'},\n",
       " {'title': 'Chase Ink Business Cash Card',\n",
       "  'store': 'Chase - Bank Advertiser\\xa0',\n",
       "  'price': '\\n                                          $500 Cash Back\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/11403699-chase-ink-business-cash-card-500-cash-back-w-3k-spent-in-1st-3-mos?src=sticky-24'},\n",
       " {'title': 'Work Pro Shop Stool',\n",
       "  'store': 'Walmart\\xa0',\n",
       "  'price': '\\n                                          $12\\n                                                                                      (83% OFF)\\n$69\\n',\n",
       "  'link': 'https://slickdeals.net/f/13171150-work-pro-shop-stool-12?src=frontpage'},\n",
       " {'title': 'Funko Pop Game of Thrones Figures&colon Arya Stark&comma Daenerys White Coat',\n",
       "  'store': 'AT&T Wireless\\xa0',\n",
       "  'price': '\\n                                          $5 each\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13171816-at-t-online-clearance-in-store-ymmv-funko-pop-tv-game-of-thrones-tyrion-lannister-with-scar-battle-armour-and-more-5?src=frontpage'},\n",
       " {'title': '1-Month Audible Trial &plus 2 Audible Originals &plus 2 Audiobooks',\n",
       "  'store': 'Audible\\xa0',\n",
       "  'price': '\\n                                          Free\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13118755-2-free-audiobooks-and-2-audible-originals-for-returning-members-ymmv?src=sticky-24'},\n",
       " {'title': 'Insignia Alkaline Batteries&colon 24-Count AA &plus 12-Count AAA w&sol Case',\n",
       "  'store': 'Best Buy\\xa0',\n",
       "  'price': '\\n                                          $7\\n                                                                                      (50% OFF)\\n$14\\n',\n",
       "  'link': 'https://slickdeals.net/f/13171324-insignia-alkaline-batteries-36-pack-24-aa-12-aaa-batteries-6-99-free-store-pickup?src=frontpage'},\n",
       " {'title': 'Plantronics Voyager 5200 Bluetooth Headset w&sol WindSmart Technology &lparRefurb&rpar',\n",
       "  'store': 'eBay\\xa0',\n",
       "  'price': '\\n                                          $30\\n                                                                                      (86% OFF)\\n$220\\n',\n",
       "  'link': 'https://slickdeals.net/f/13156690-plantronics-voyager-5200-bluetooth-headset-w-windsmart-technology-refurb-30-free-shipping?src=frontpage'},\n",
       " {'title': 'Chase Sapphire Preferred Card&colon Spend &dollar4K on Purchases & Earn',\n",
       "  'store': 'Chase - Bank Advertiser\\xa0',\n",
       "  'price': '\\n                                          60,000 Points\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/12940198-chase-sapphire-preferred-card-spend-4k-on-purchases-earn-60-000-points-within-1st-3-months?src=sticky-24'},\n",
       " {'title': 'Zinus Cynthia 14\" MyEuro SmartBase Wooden Slat Mattress Foundation &lparFull&rpar',\n",
       "  'store': 'Walmart\\xa0',\n",
       "  'price': '\\n                                          $52.30\\n                                                                                      (34% OFF)\\n$79\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170883-zinus-cynthia-14-inch-myeuro-smartbase-full-53-free-prime-shipping?src=frontpage'},\n",
       " {'title': '&dollar25 Chipotle Gift Card &lparEmail Delivery&rpar',\n",
       "  'store': 'eBay\\xa0',\n",
       "  'price': '\\n                                          $20\\n                                                                                      (20% OFF)\\n$25\\n',\n",
       "  'link': 'https://slickdeals.net/f/13172128-25-chipotle-gift-card-for-20-email-delivery?src=frontpage'},\n",
       " {'title': 'Chase Ink Business Preferred Card',\n",
       "  'store': 'Chase - Bank Advertiser\\xa0',\n",
       "  'price': '\\n                                          80K Points\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/9205591-chase-ink-business-preferred-card-80k-points-w-5k-spent-in-1st-3-mos?src=sticky-24'},\n",
       " {'title': '&dollar200 Carnival Cruise Gift Card &lparEmail Delivery&rpar',\n",
       "  'store': 'NeweggFlash\\xa0',\n",
       "  'price': '\\n                                          $185\\n                                                                                      (8% OFF)\\n$200\\n',\n",
       "  'link': 'https://slickdeals.net/f/13169656-200-carnival-cruise-gift-card-email-delivery-for-185?src=frontpage'},\n",
       " {'title': '20-Pack AmazonBasics AAA Alkaline Batteries',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $2.90\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13172065-amazonbasics-aaa-1-5-volt-performance-alkaline-batteries-pack-of-20-packaging-may-vary-aaa-2-7?src=frontpage'},\n",
       " {'title': 'Bank of America® Cash Rewards Credit Card',\n",
       "  'store': 'Bank of America - Bank Advertiser\\xa0',\n",
       "  'price': '\\n                                          $200 Bonus Offer\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13004074-bank-of-america-cash-rewards-credit-card-200-bonus-offer-w-1k-in-eligible-purchases?src=sticky-24'},\n",
       " {'title': 'Hyper Tough 20V MAX Cordless Pole Saw',\n",
       "  'store': 'Walmart\\xa0',\n",
       "  'price': '\\n                                          $45\\n                                                                                      (59% OFF)\\n$110\\n',\n",
       "  'link': 'https://slickdeals.net/f/13171981-hyper-tough-20v-max-cordless-pole-saw-45-free-store-pickup?src=frontpage'},\n",
       " {'title': '1-Year of The Economist Magazine &lpar51-Issues&comma Print or Digital&rpar',\n",
       "  'store': 'DiscountMags\\xa0',\n",
       "  'price': '\\n                                          $48\\n                                                                                      (73% OFF)\\n$179\\n',\n",
       "  'link': 'https://slickdeals.net/f/13111738-1-year-of-the-economist-magazine-51-issues-print-or-digital-48?src=frontpage'},\n",
       " {'title': 'Chase Ink Business Unlimited Credit Card',\n",
       "  'store': 'Chase - Bank Advertiser\\xa0',\n",
       "  'price': '\\n                                          $500 Bonus\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/11621423-chase-ink-business-unlimited-credit-card-500-bonus-after-3k-spent-in-3-months?src=sticky-24'},\n",
       " {'title': 'Anker Roav SmartCharge F0 Bluetooth FM Transmitter 2-Port USB Car Charger',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $11\\n                                                                                      (35% OFF)\\n$17\\n',\n",
       "  'link': 'https://slickdeals.net/f/13150627-anker-roav-smartcharge-f0-bluetooth-fm-transmitter-2-port-usb-car-charger-11?src=frontpage'},\n",
       " {'title': 'Chucky&colon Complete 7-Movie Collection &lparBlu-ray&rpar',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $20\\n                                                                                      (60% OFF)\\n$50\\n',\n",
       "  'link': 'https://slickdeals.net/f/13163179-chucky-complete-7-movie-collection-blu-ray-19-99-via-amazon?src=frontpage'},\n",
       " {'title': 'HSBC Direct Savings Account&colon Earn 2&period30&percnt APY &plus Extra',\n",
       "  'store': 'HSBC Direct Savings\\xa0',\n",
       "  'price': '\\n                                          $125 SD Bonus\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/12992002-hsbc-direct-savings-account-earn-2-30-apy-extra-125-sd-bonus-member-fdic?src=sticky-24'},\n",
       " {'title': 'ASUS VivoBook F510QA&colon AMD A12-9720P&comma 15&period6\" 1080p&comma 4GB Ram&comma 128GB SSD',\n",
       "  'store': 'Walmart\\xa0',\n",
       "  'price': '\\n                                          $259\\n                                                                                      (35% OFF)\\n$399\\n',\n",
       "  'link': 'https://slickdeals.net/f/13169302-asus-vivobook-f510qa-amd-a12-9720p-15-6-1080p-4gb-ram-128gb-ssd-259-free-shipping?src=frontpage'},\n",
       " {'title': 'Yokohama Avid Touring-S All-Season Tire &lpar225&sol55R17 97T&rpar',\n",
       "  'store': 'Walmart\\xa0',\n",
       "  'price': '\\n                                          $77.80\\n                                                                                      (30% OFF)\\n$110\\n',\n",
       "  'link': 'https://slickdeals.net/f/13171033-yokohama-avid-touring-s-all-season-tire-225-55r17-97t-77-80-free-shipping?src=frontpage'},\n",
       " {'title': 'Wells Fargo Cash Wise Visa® Card',\n",
       "  'store': 'Wells Fargo - Bank Advertiser\\xa0',\n",
       "  'price': '\\n                                          $200 Bonus\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/10076220-wells-fargo-cash-wise-visa-card-200-bonus-1-5-cash-rewards?src=sticky-24'},\n",
       " {'title': 'Milwaukee M12 12V Li-ion 3&sol8\" Crown Stapler w&sol 2x Batteries&comma Charger&comma Bag',\n",
       "  'store': 'Home Depot\\xa0',\n",
       "  'price': '\\n                                          $99\\n                                                                                      (67% OFF)\\n$298\\n',\n",
       "  'link': 'https://slickdeals.net/f/13171774-milwaukee-m12-12v-li-ion-3-8-crown-stapler-w-2x-batteries-charger-bag-99-free-shipping?src=frontpage'},\n",
       " {'title': 'Verizon Customers &lparNew Lines&rpar&colon 128GB Moto Z4 &dollar5&solmo on 24-Mo&period Payment Plan or',\n",
       "  'store': 'Best Buy\\xa0',\n",
       "  'price': '\\n                                          $160\\n                                                                                      (76% OFF)\\n$500\\n',\n",
       "  'link': 'https://slickdeals.net/f/13145854-verizon-customers-new-lines-128gb-moto-z4-5-mo-on-24-mo-payment-plan-or-160-w-activation-free-store-pickup?src=frontpage'},\n",
       " {'title': 'Verizon Fios&colon 100&sol100 Mbps Internet',\n",
       "  'store': 'Verizon Fios\\xa0',\n",
       "  'price': '\\n                                          $39.99/month\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/e/10817763-verizon-fios-100-100-mbps-internet-39-99-month-auto-pay-required-new-customers-only?src=sticky-24'},\n",
       " {'title': '8TB WD Red NAS 3&period5\" Internal Hard Drive',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $185\\n                                                                                      (26% OFF)\\n$251\\n',\n",
       "  'link': 'https://slickdeals.net/f/13171060-wd-red-8tb-nas-184-99?src=frontpage'},\n",
       " {'title': 'Digital 4K UHD&colon Batman vs TMNT&comma Fantastic Beasts&colon Crimes of Grindelwald',\n",
       "  'store': 'VUDU\\xa0',\n",
       "  'price': '\\n                                          $8 each\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13171507-batman-vs-teenage-mutant-ninja-turtles-or-fantastic-beasts-the-crimes-of-grindelwald-digital-4k-uhd-film-7-99-each-via-vudu?src=frontpage'},\n",
       " {'title': 'Blue Cash Everyday® Card from American Express &lparterms apply&rpar',\n",
       "  'store': 'Amex - Bank Advertiser\\xa0',\n",
       "  'price': '\\n                                          Earn $150 Back\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/11916935-blue-cash-everyday-card-from-american-express-terms-apply-earn-150-back-w-1k-spent-in-1st-3-mos?src=sticky-24'},\n",
       " {'title': 'Wells Fargo Propel® Card  &lpar&dollar0 Annual Fee&rpar',\n",
       "  'store': 'Wells Fargo - Bank Advertiser\\xa0',\n",
       "  'price': '\\n                                          30K Bonus Pts\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/11813555-wells-fargo-propel-card-0-annual-fee-30k-bonus-pts-w-3k-spent-in-1st-3-mos?src=sticky-24'},\n",
       " {'title': 'Ozark Trail 10&apos x 10&apos Instant Screen House',\n",
       "  'store': 'Walmart\\xa0',\n",
       "  'price': '\\n                                          $59\\n                                                                                      (40% OFF)\\n$99\\n',\n",
       "  'link': 'https://slickdeals.net/f/13169854-ozark-trail-10-x-10-instant-screen-house-canopy-59-free-shipping?src=frontpage'},\n",
       " {'title': 'Mainstays 3-Piece Brooklyn Counter Height Dining Set &lparGray&rpar',\n",
       "  'store': 'Walmart\\xa0',\n",
       "  'price': '\\n                                          $35.60\\n                                                                                      (70% OFF)\\n$119\\n',\n",
       "  'link': 'https://slickdeals.net/f/13171099-mainstays-3-piece-brooklyn-counter-height-dining-set-gray-35-60-free-s-h?src=frontpage'},\n",
       " {'title': 'Kingdom Rush Origins &lparAndroid or iOS Game App&rpar',\n",
       "  'store': 'Apple iTunes\\xa0',\n",
       "  'price': '\\n                                          $1\\n                                                                                      (67% OFF)\\n$3\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170880-kingdom-rush-origins-android-ios-app-0-99-google-play-itunes?src=frontpage'},\n",
       " {'title': '2x 5-Count 5&period3oz&period Perfect Bar Kids Bar Coupon',\n",
       "  'store': 'Perfect Bar\\xa0',\n",
       "  'price': '\\n                                          Free\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13170868-2-free-boxes-of-perfect-kids-snacks?src=frontpage'},\n",
       " {'title': 'Sam&aposs Club Members&colon 100-Piece Tytan Magnetic Learning Tiles Building Set',\n",
       "  'store': \"Sam's Club\\xa0\",\n",
       "  'price': '\\n                                          $30\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13170286-sam-s-club-member-tytan-magnetic-learning-tiles-building-set-with-100-pieces-29-98-free-ship-for-plus?src=frontpage'},\n",
       " {'title': 'Staples Coupon for Online Orders&colon &dollar50 Off &dollar200&plus',\n",
       "  'store': 'Staples\\xa0',\n",
       "  'price': '\\n                                          $20 Off $100+\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13168873-20-off-100-online-order-50-off-200-online-orders-at-staples-com?src=frontpage'},\n",
       " {'title': '3-Pack Mrs&period Meyer’s Clean Day Multi-Surface Everyday Cleaner &lparLavender&rpar',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $8\\n                                                                                  $12\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170892-amazon-s-s-mrs-meyer-s-clean-day-multi-surface-everyday-cleaner-lavender-16-oz-3-pack-7-96-free-s-h?src=frontpage'},\n",
       " {'title': 'Google Home Hub 7\" Smart Display &lparChalk or Charcoal&rpar',\n",
       "  'store': 'Rakuten\\xa0',\n",
       "  'price': '\\n                                          $61\\n                                                                                      (59% OFF)\\n$149\\n',\n",
       "  'link': 'https://slickdeals.net/f/13169734-google-home-hub-smart-display-chalk-or-charcoal-60-98-free-shipping?src=frontpage'},\n",
       " {'title': 'Xbox One Digital&colon Wonder Boy&colon The Dragon&aposs Trap &dollar10&comma The Council Complete Season',\n",
       "  'store': 'Microsoft Store\\xa0',\n",
       "  'price': '\\n                                          $7.50\\n                                                                                  $30\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170907-xbox-one-digital-wonder-boy-the-dragon-s-trap-10-the-council-complete-season-7-50-more-xbl-gold-required?src=frontpage'},\n",
       " {'title': 'Swych App&colon &dollar50 Nintendo eShop Gift Card &lparDigital&rpar',\n",
       "  'store': 'Swych\\xa0',\n",
       "  'price': '\\n                                          $40\\n                                                                                  $50\\n',\n",
       "  'link': 'https://slickdeals.net/f/13169722-50-nintendo-eshop-gc-for-40-new-swych-users-only?src=frontpage'},\n",
       " {'title': 'Spider-Man&colon Into the Spider-Verse &lpar4K Digital&rpar &plus &dollar8 Credit for Spider-Man&colon FFH',\n",
       "  'store': 'FandangoNOW\\xa0',\n",
       "  'price': '\\n                                          $10\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13170661-spider-man-into-the-spider-verse-digital-4k-uhd-8-fandango-movie-cash-offer-for-spider-man-far-from-home-9-99-more?src=frontpage'},\n",
       " {'title': '24-Pack of 8oz V8 V-Fusion Juice &lparStrawberry Banana&rpar',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $11.95\\n                                                                                      (25% OFF)\\n$16\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170739-24-pack-of-8oz-v8-v-fusion-juice-strawberry-banana-11-94-or-less-w-s-s-free-shipping-amazon?src=frontpage'},\n",
       " {'title': 'ASUS 15&period6\" TUF Gaming Laptop&colon Ryzen 5-3550H&comma 512GB SSD&comma GTX 1660Ti',\n",
       "  'store': 'Micro Center\\xa0',\n",
       "  'price': '\\n                                          $800\\n                                                                                      (20% OFF)\\n$999\\n',\n",
       "  'link': 'https://slickdeals.net/f/13167262-asus-tuf-fx505du-mb53-gtx-1660-ti-6gb-amd-3550h-8gb-ram-512-gb-ssd-799-98?src=frontpage'},\n",
       " {'title': 'DuroMax XP4850EH Hybrid Portable Propane&solGas Powered Generator',\n",
       "  'store': 'eBay\\xa0',\n",
       "  'price': '\\n                                          $300\\n                                                                                      (70% OFF)\\n$1000\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170781-299-duromax-xp4850eh-hybrid-portable-dual-fuel-propane-gas-camping-rv-generator?src=frontpage'},\n",
       " {'title': 'Logitech G703 Lightspeed Wireless Gaming Mouse &lparBlack&rpar',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $55\\n                                                                                  $100\\n',\n",
       "  'link': 'https://slickdeals.net/f/13168732-logitech-g703-lightspeed-wireless-gaming-mouse-black-55-free-shipping?src=frontpage'},\n",
       " {'title': 'Amex Offer&colon Spend &dollar200&plus on Room Rate&solCharges at Marriott Bonvoy Hotels&comma Get',\n",
       "  'store': 'Amex Offers\\xa0',\n",
       "  'price': '\\n                                          $40 Credit\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13170766-amex-offers-spend-200-at-marriott-get-40-as-a-statement-credit?src=frontpage'},\n",
       " {'title': 'Infant Optics DXR-8 3&period5\" Video Baby Monitor &lparUsed - Good&rpar',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $69\\n                                                                                      (58% OFF)\\n$166\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170919-infant-optics-dxr-8-video-baby-monitor-used-good-condition-69-02?src=frontpage'},\n",
       " {'title': 'Hanna & Henri&colon The Party & The Robot Kids Apps &lpariOS or Android&rpar',\n",
       "  'store': 'Apple iTunes\\xa0',\n",
       "  'price': '\\n                                          Free\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13168990-hanna-henri-the-party-the-robot-kids-apps-android-ios-for-free?src=frontpage'},\n",
       " {'title': 'Audible Members&colon Sale on Select Audiobooks',\n",
       "  'store': 'Audible\\xa0',\n",
       "  'price': '\\n                                          2 for 1 Credit\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13167691-audible-never-stop-learning-2-for-1-credit-sale-members-only?src=frontpage'},\n",
       " {'title': 'adidas Men&aposs & Women&aposs UltraBOOST 19 Running Shoes &lparvarious colors&rpar',\n",
       "  'store': 'JackRabbit\\xa0',\n",
       "  'price': '\\n                                          $108\\n                                                                                  $180\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170637-adidas-ultraboost-19-107-98-free-shipping?src=frontpage'},\n",
       " {'title': 'Tag Heuer Formula 1 Automatic Chronograph Watch on Bracelet',\n",
       "  'store': 'WatchMaxx\\xa0',\n",
       "  'price': '\\n                                          $1650\\n                                                                                  $2850\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170166-tag-heuer-formula-1-automatic-chronograph-on-bracelet-1650-or-special-ed-pvd-ti-1890-free-s-h?src=frontpage'},\n",
       " {'title': '27\" LG 27GK750F-B 1080p 240Hz FreeSync Gaming Monitor',\n",
       "  'store': 'BuyDig\\xa0',\n",
       "  'price': '\\n                                          $249\\n                                                                                      (55% OFF)\\n$550\\n',\n",
       "  'link': 'https://slickdeals.net/f/13169653-27-lg-27gk750f-b-1080p-240hz-freesync-gaming-monitor-249-free-s-h?src=frontpage'},\n",
       " {'title': 'Kindle Unlimited Membership &lparDigital Gift&rpar&colon 1-Year &dollar80&period30&comma 2-year',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $143.80\\n                                                                                      (40% OFF)\\n$240\\n',\n",
       "  'link': 'https://slickdeals.net/f/13130245-kindle-unlimited-membership-digital-gift-1-year-80-30-2-year-143-80-more?src=frontpage'},\n",
       " {'title': 'Add-on Item&colon 20-Ct Martha Stewart Holiday Card Kit w&sol Envelope Seals',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          from $2.40\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13169845-add-on-item-20-ct-martha-stewart-holiday-card-kit-w-envelope-seals-from-2-40?src=frontpage'},\n",
       " {'title': '64GB Microsoft Surface Go 10\" &plus Office 365',\n",
       "  'store': 'Rakuten\\xa0',\n",
       "  'price': '\\n                                          $313.65\\n                                                                                      (33% OFF)\\n$470\\n',\n",
       "  'link': 'https://slickdeals.net/f/13169749-64gb-microsoft-surface-go-10-office-365-313-65-free-s-h?src=frontpage'},\n",
       " {'title': 'Archer&colon The Complete Seasons 1-9 &lparDigital HD&rpar',\n",
       "  'store': 'Apple iTunes\\xa0',\n",
       "  'price': '\\n                                          $30\\n                                                                                      (70% OFF)\\n$100\\n',\n",
       "  'link': 'https://slickdeals.net/f/13170253-archer-the-complete-seasons-1-9-digital-hd-29-99-itunes?src=frontpage'},\n",
       " {'title': 'Efluky USB 3 Speed Rechargeable Portable Fan &lparVarious Colors&rpar',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $9.90\\n                                                                                      (34% OFF)\\n$15\\n',\n",
       "  'link': 'https://slickdeals.net/f/13169683-efluky-3-speeds-mini-desk-fan-rechargeable-battery-operated-fan-with-led-light-and-2200mah-battery-9-89?src=frontpage'},\n",
       " {'title': 'Petco Original Loofa 6\" Mini Terry Dog Toy &lparRandom Color&rpar',\n",
       "  'store': 'Amazon\\xa0',\n",
       "  'price': '\\n                                          $1.75\\n                                                                              ',\n",
       "  'link': 'https://slickdeals.net/f/13169806-6-squeaker-dog-toy-1-75-add-on?src=frontpage'},\n",
       " {},\n",
       " {'title': '', 'store': '\\xa0'}]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "list_of_products = []\n",
    "\n",
    "for product in products:\n",
    "    \n",
    "    product_dict = {}\n",
    "    \n",
    "    try:\n",
    "        title = product.find(class_='itemTitle')\n",
    "        product_dict['title'] = title.text\n",
    "        store = product.find(class_='itemStore')\n",
    "        product_dict['store'] = store.text\n",
    "        price = product.find(class_='itemPrice')\n",
    "        product_dict['price'] = price.text\n",
    "        url = \"https://slickdeals.net\"\n",
    "        product_dict['link'] = url+product.find(class_='itemTitle').attrs['href']\n",
    "    except:\n",
    "        print(\" \")\n",
    "        \n",
    "        \n",
    "    list_of_products.append(product_dict)\n",
    "    \n",
    "list_of_products"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>link</th>\n",
       "      <th>price</th>\n",
       "      <th>store</th>\n",
       "      <th>title</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>https://slickdeals.net/f/13171879-children-s-p...</td>\n",
       "      <td>fro...</td>\n",
       "      <td>The Children's Place</td>\n",
       "      <td>The Children&amp;aposs Place&amp;colon Up to 80&amp;percnt...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>https://slickdeals.net/f/13142320-50-count-wil...</td>\n",
       "      <td>$5....</td>\n",
       "      <td>Walmart</td>\n",
       "      <td>50-Ct Wilton 12\" Disposable Cake Decorating Pa...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>https://slickdeals.net/f/11403699-chase-ink-bu...</td>\n",
       "      <td>$50...</td>\n",
       "      <td>Chase - Bank Advertiser</td>\n",
       "      <td>Chase Ink Business Cash Card</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>https://slickdeals.net/f/13171150-work-pro-sho...</td>\n",
       "      <td>$12...</td>\n",
       "      <td>Walmart</td>\n",
       "      <td>Work Pro Shop Stool</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                link  \\\n",
       "0                                                NaN   \n",
       "1  https://slickdeals.net/f/13171879-children-s-p...   \n",
       "2  https://slickdeals.net/f/13142320-50-count-wil...   \n",
       "3  https://slickdeals.net/f/11403699-chase-ink-bu...   \n",
       "4  https://slickdeals.net/f/13171150-work-pro-sho...   \n",
       "\n",
       "                                               price  \\\n",
       "0                                                NaN   \n",
       "1                                             fro...   \n",
       "2                                             $5....   \n",
       "3                                             $50...   \n",
       "4                                             $12...   \n",
       "\n",
       "                      store                                              title  \n",
       "0                                                                               \n",
       "1     The Children's Place   The Children&aposs Place&colon Up to 80&percnt...  \n",
       "2                  Walmart   50-Ct Wilton 12\" Disposable Cake Decorating Pa...  \n",
       "3  Chase - Bank Advertiser                        Chase Ink Business Cash Card  \n",
       "4                  Walmart                                 Work Pro Shop Stool  "
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.DataFrame(list_of_products)\n",
    "df['price'] = df['price'].str.replace(\"\\n\", \" \")\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'03PM'"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import datetime\n",
    "right_now = datetime.datetime.now()\n",
    "right_now = str(right_now.strftime(\"%Y-%m-%d-%I%p\"))\n",
    "str(right_now)\n",
    "right_now_header = datetime.datetime.now()\n",
    "right_now_header = str(right_now_header.strftime(\"%I%p\"))\n",
    "right_now_header\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv('slick-deals-products-'+ right_now +'.csv' , index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'slick-deals-products-2019-06-25-03PM.csv'"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filename = 'slick-deals-products-'+ right_now +'.csv'\n",
    "filename"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "response = requests.post(\n",
    "        \"https://api.mailgun.net/v3/sandbox5ec0ddffbdba4001b8214f98622fe1d0.mailgun.org/messages\",\n",
    "        auth=(\"api\", \"6fdb842f47e65d63dd61f10b38545e63-2b778fc3-8157d877\"),\n",
    "        files=[(\"attachment\", open(filename))],\n",
    "        data={\"from\": \"Excited User <mailgun@sandbox5ec0ddffbdba4001b8214f98622fe1d0.mailgun.org>\",\n",
    "              \"to\": [\"giovanacfleck@gmail.com\"],\n",
    "              \"subject\": \"Here is your \"+ right_now_header+\" briefing\",\n",
    "              \"text\": filename})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
